# Generated by Django 4.2.15 on 2024-08-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_user'),
        ('services', '0002_alter_course_full_price_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='clients.client'),
        ),
    ]
