# Generated by Django 4.2.15 on 2024-09-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course_subcategory',
        ),
        migrations.AddField(
            model_name='course',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='services.category'),
        ),
        migrations.DeleteModel(
            name='CourseSubcategory',
        ),
        migrations.AddField(
            model_name='coursemodules',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='services.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course_module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='services.coursemodules'),
            preserve_default=False,
        ),
    ]
