# Generated by Django 4.2.15 on 2024-09-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_coursemodules_remove_lesson_course_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='have_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'Англійська')], default='uk', max_length=255),
            preserve_default=False,
        ),
    ]
