# Generated by Django 4.2.15 on 2024-09-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_course_have_certificate_course_is_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
    ]
