# Generated by Django 4.2.16 on 2024-09-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_previews/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
