# Generated by Django 4.2.16 on 2024-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_course_preview_image_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
