# Generated by Django 4.2.16 on 2024-09-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='preview_image',
            new_name='preview',
        ),
    ]
