# Generated by Django 4.2.16 on 2024-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_preview_image_course_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Починаючий'), ('middle', 'Середній'), ('expert', 'Продвинутий')], max_length=255, null=True),
        ),
    ]
