# Generated by Django 4.2.16 on 2024-09-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_course_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
