# Generated by Django 4.2.16 on 2024-09-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_courseinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='preview_image',
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='preview_videos/%Y/%m/%d/'),
        ),
    ]
