# Generated by Django 4.2.16 on 2024-09-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_courseinfo_workload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='preview_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
