# Generated by Django 4.2.16 on 2024-10-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_coursemodules_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
